/**
 * app直下のlayout.tsxはroot layoutとして見做される
 * アプリケーション全体に適用させたいことを記載する
 */
import NavBar from './components/nav-bar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

// head.tsxが廃止になったため、代わりにmetadataを追加する
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
